name: NegraTec
description: Este site está em construção... NÃO COMPARTILHE. Negra Tec é um projeto que visa colocar em contato mulheres negras interessadas na área de TI no Brasil.
paginate: 10
# baseurl: '/DopeTrope-Jekyll-Theme'
