# Site settings
title: Negra Tec
email: roselma.mendes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Negra Tec é um projeto que visa colocar em contato mulheres negras interessadas na área de TI no Brasil.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://negratec.github.io" # the base hostname & protocol for your site
twitter_username: roselmamendes
github_username:  negratec

# Build settings
markdown: kramdown
